# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# https://developers.facebook.com/docs/internationalization#locales
# OG image is 1200 pixels x 627 pixels (1.91/1 ratio) -> don’t exceed the 5MB size limit.
#variables
#repository is required/helps github-pages gem it's a good idea to include
# need to call api to find it from list of repos

repository: 131331861
repository_url: https://github.com/danyn/acdl
url: https://danyn.github.io
baseurl: /acdl
permalink: /:categories/:title/
country: CA
lang: en
title: Creative Dental Labs Specializes in Crowns and Bridges
description: We provide fast turnarounds on diagnostic wax-ups
company_name: Creative Dental Laboratory
company_nickname: Creative Dental Labs
nav: navs/nav-default.html
logo: /assets/logo.png
social_image: assets/share_site.jpg
email: your-email@example.com
tel_pretty: (250) 595-1314
tel: 2505951314
author: Daniel Eisen
twitter: true
twitter_username: twitterMan
github_username: daniel-eisen

# Explicitly say which pages to include in the nav
header_pages:
  - pages/layouts/index.html
  - pages/site-vars/site-vars.html
  - pages/about/about.md
  - pages/contact/contact.html
  - pages/restorations/restorations.html
  - dropdown: Topics
    dropdownItems:
      - pages/topics/topic-1/index.html
      - pages/topics/topic-2/index.html

 
 


# Information for facebook pixil and marketing functions
facebook:
  admins: 3333
  app_id: 1111
  publisher: 2222
  locale: en_CA 
# Information for website verification codes often written into the the document head
webmaster_verifications:
  google: 938475394875
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""



#schema.org settings which can also be used to reference these values in the site markup and rich snippets
schema_org:
  type: MedicalBusiness
  city: Victoria
  province: BC
  postalCode: V8R 1J5
  streetAddress: 1780 Fort Street Victoria


# Build settings
debug: no
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package-lock.json
  - package.json
  - README.md
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - pages/about/about.scss
  - pages/contact/contact.scss
  - pages/restorations/restorations.scss
  - pages/home/home.scss
  

# added while trying to fix a auth problem related to gh-pages gem I don't know what this does
# github: [metadata]